name: Unity Tests

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: "3.9"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Test with pytest and calculate coverage
        run: |
          poetry run pytest --cov-report "xml:coverage.xml" --cov=.
          
      - name: Upload coverage report to Codacy
        run: |

          export CODACY_API_TOKEN=${{secrets.CODACY_API_TOKEN}}
          export CODACY_ORGANIZATION_PROVIDER=gh
          export CODACY_USERNAME=maui-software
          export CODACY_PROJECT_NAME=maui-software
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

